baseURL = "https://philipgreco.com/"
title   = "Philip Greco"
languageCode = "en-us"
theme = "hugo-theme-hello-friend-ng"

enableRobotsTXT = true
enableEmoji     = true

[pagination]
  pagerSize = 10

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  description = "Philip Greco - Sr. DevOps Engineer"

  homeSubtitle = "Sr. DevOps Engineer"

  enableThemeToggle    = true
  enableSharingButtons = false
  enableReadingTime    = true

  [params.author]
    name = "Philip Greco"

  [params.portrait]
    path     = "/img/AI_Yoda.png"
    alt      = "Philip Greco"
    maxWidth = "150px"

  [params.logo]
    logoMark          = "p@site ➜ "
    logoText          = " /home"
    logoHomeLink      = "/"
    logoCursorColor   = "#9b59b6"

  [params.footer]
    copyright = false
    author    = false

  [[params.social]]
    name = "email"
    url  = "mailto:philip.d.greco@gmail.com"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/philip-greco-662a0558"

  [[params.social]]
    name = "github"
    url  = "https://github.com/PDGIII"

[languages]
  [languages.en]
    weight    = 1
    copyright = "Philip Greco"
  [languages.en.params]
    subtitle = "Sr. DevOps Engineer"

[menu]
  [[menu.main]]
    identifier = "weather"
    name       = "⛅"
    url        = "https://weather.philipgreco.com/"
