name: Build and Push website

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: homelab-k8s-website
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/pdgiii/website:latest
            ghcr.io/pdgiii/website:${{ github.sha }}
